/*
CREATE TABLE TB_REGION
(
  REGION_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
  REGION_TYPE VARCHAR(10)
);
CREATE TABLE TB_REGION_TRANS
(
  TRANS_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
  REGION_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
  TRANS_TYPE VARCHAR(10),
  TITLE VARCHAR(100),
  CONTENT VARCHAR(4000)
);*/